import { DOUBLE_STRING, HASH_COMMENT, SINGLE_STRING, defineLang } from './patterns.js';

const KEYWORDS = new Set([
  `alias`,
  `and`,
  `begin`,
  `break`,
  `case`,
  `class`,
  `def`,
  `defined?`,
  `do`,
  `else`,
  `elsif`,
  `end`,
  `ensure`,
  `for`,
  `if`,
  `in`,
  `module`,
  `next`,
  `not`,
  `or`,
  `redo`,
  `rescue`,
  `retry`,
  `return`,
  `self`,
  `super`,
  `then`,
  `unless`,
  `until`,
  `when`,
  `while`,
  `yield`,
  `raise`,
  `require`,
  `include`,
  `extend`,
  `attr_reader`,
  `attr_writer`,
  `attr_accessor`,
  `puts`,
  `print`,
]);

export const definition = defineLang({
  comments: [HASH_COMMENT],
  strings: [DOUBLE_STRING, SINGLE_STRING],
  keywords: KEYWORDS,
  constants: new Set([`true`, `false`, `nil`]),
});

export const aliases = [`ruby`, `rb`];
