/**
 * @fileoverview PHP language definition for the syntax highlighter.
 */

import {
  BLOCK_COMMENT,
  DOUBLE_STRING,
  HASH_COMMENT,
  LINE_COMMENT,
  SINGLE_STRING,
  defineLang,
} from './patterns.js';

const KEYWORDS = new Set([
  'abstract',
  'and',
  'array',
  'as',
  'break',
  'callable',
  'case',
  'catch',
  'class',
  'clone',
  'const',
  'continue',
  'declare',
  'default',
  'die',
  'do',
  'echo',
  'else',
  'elseif',
  'empty',
  'enddeclare',
  'endfor',
  'endforeach',
  'endif',
  'endswitch',
  'endwhile',
  'eval',
  'exit',
  'extends',
  'final',
  'finally',
  'fn',
  'for',
  'foreach',
  'function',
  'global',
  'goto',
  'if',
  'implements',
  'include',
  'include_once',
  'instanceof',
  'insteadof',
  'interface',
  'isset',
  'list',
  'match',
  'namespace',
  'new',
  'or',
  'print',
  'private',
  'protected',
  'public',
  'readonly',
  'require',
  'require_once',
  'return',
  'static',
  'switch',
  'throw',
  'trait',
  'try',
  'unset',
  'use',
  'var',
  'while',
  'xor',
  'yield',
]);

export const definition = defineLang({
  comments: [BLOCK_COMMENT, LINE_COMMENT, HASH_COMMENT],
  strings: [DOUBLE_STRING, SINGLE_STRING],
  keywords: KEYWORDS,
  constants: new Set(['true', 'false', 'null', 'TRUE', 'FALSE', 'NULL']),
});

export const aliases = ['php'];
