/**
 * @fileoverview SQL language definition for the syntax highlighter.
 *
 * Keywords are stored upper-cased; the `caseInsensitive` flag tells
 * the generic tokeniser to upper-case identifiers before lookup.
 */

import { BLOCK_COMMENT, DASH_COMMENT, SINGLE_STRING, defineLang } from './patterns.js';

const KEYWORDS = new Set(
  [
    'select',
    'from',
    'where',
    'and',
    'or',
    'not',
    'in',
    'is',
    'null',
    'insert',
    'into',
    'values',
    'update',
    'set',
    'delete',
    'create',
    'alter',
    'drop',
    'table',
    'index',
    'view',
    'database',
    'schema',
    'grant',
    'revoke',
    'join',
    'inner',
    'outer',
    'left',
    'right',
    'cross',
    'on',
    'as',
    'order',
    'by',
    'group',
    'having',
    'limit',
    'offset',
    'union',
    'all',
    'distinct',
    'between',
    'like',
    'exists',
    'case',
    'when',
    'then',
    'else',
    'end',
    'begin',
    'commit',
    'rollback',
    'primary',
    'key',
    'foreign',
    'references',
    'constraint',
    'default',
    'check',
    'unique',
    'asc',
    'desc',
    'count',
    'sum',
    'avg',
    'min',
    'max',
    'if',
    'declare',
    'cursor',
    'fetch',
    'open',
    'close',
    'with',
    'recursive',
    'temporary',
    'trigger',
    'procedure',
    'function',
    'returns',
    'return',
  ].map((k) => k.toUpperCase()),
);

const TYPES = new Set([
  'INT',
  'INTEGER',
  'BIGINT',
  'SMALLINT',
  'TINYINT',
  'FLOAT',
  'DOUBLE',
  'DECIMAL',
  'NUMERIC',
  'REAL',
  'BOOLEAN',
  'BOOL',
  'CHAR',
  'VARCHAR',
  'TEXT',
  'BLOB',
  'DATE',
  'TIME',
  'DATETIME',
  'TIMESTAMP',
  'SERIAL',
]);

export const definition = defineLang({
  comments: [BLOCK_COMMENT, DASH_COMMENT],
  strings: [SINGLE_STRING],
  keywords: KEYWORDS,
  types: TYPES,
  constants: new Set(['TRUE', 'FALSE', 'NULL']),
  caseInsensitive: true,
});

export const aliases = ['sql', 'mysql', 'postgresql', 'sqlite'];
